name: Validate Packer Script
on:
  pull_request:
    branches:
      - main
jobs:
  validate_packer:
    name: Validate Packer Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest
      - name: Initialize Packer
        working-directory: infra/packer/
        run: packer init .
      - name: Check Packer Formatting
        working-directory: infra/packer/
        run: |
          if packer fmt -check .; then
            echo "Packer formatting is correct."
          else
            echo "Packer format check has failed. Run 'packer fmt' in local to fix formatting."
            exit 1
          fi
      - name: Validate Packer Configuration
        working-directory: infra/packer/
        run: packer validate .
